[book]
authors = ["Sebastian Porto"]
language = "en"
multilingual = false
src = "src"
title = "Elm Patterns"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/sporto/elm-patterns"
site-url = "/elm-patterns/"

[build]
build-dir = "public"

